services:
  postgres:
    # psql -hlocalhost -p5000 -Upostgres -dpostgres
    container_name: postgres
    restart: always
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:5432"
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - task-3-network

  php-web:
    container_name: php-web
    restart: always
    build:
      context: ./application
      dockerfile: Dockerfile.dev
    environment:
      DB_CONNECTION: ${DB_CONNECTION_LARAVEL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TRUST_KEY: ${TRUST_KEY}
    volumes:
      - ./application:/var/www/html
    networks:
      - task-3-network
    expose:
      - 8000
      - 80
      - 5173
    ports:
      - "8000:8000"
      - "80:80"
      - "5173:5173"

networks:
  task-3-network:
    driver: bridge