FROM node:22.11.0

WORKDIR /usr/src/app

COPY . .

# Garante permissões de execução para o script
RUN chmod +x /usr/src/app/afterbuild-dev.sh

# Comando para rodar o script
CMD ["/bin/bash", "/usr/src/app/afterbuild-dev.sh"]